# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 076dfe77592a9fbe8114b2dd22c9fba7761fb2aaa61f9c3a6ce3403ba378cce93c5d11476d2595954d8928acaa0790c691e2c6534bc5f7a3dac8404f8fe00b6c

test:
  secret_key_base: 857ecd10e9311c14c911cfe18f6442945208d58e9bd146a04bf2d0011c8005db58d62478b370674c7adc2c27112e5a1c1882d0fd522f4fcf423348b5e56a244c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
